---

- name: install packages required to be an audio_source
  become: yes
  apt:
    state: latest
    name:
      - ffmpeg
      # for NetworkManager in audio_source
      - python3-dbus
      - libnm-dev
