{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(up * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Coretemp (℃)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Write (KB/s)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m]) / 1024 / 60 * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Available (GB)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "-node_filesystem_avail_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024 * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "WiFi RSSI (dBm)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_wifi_station_signal_dbm * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "node_load1 * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "room * on(instance) group_left(nodename) (node_uname_info)"
    }
   ]
  },
  {
   "title": "Memory Free (GB)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "-node_memory_MemFree_bytes / 1024 / 1024 / 1024 * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}