---

- name: create artwork directory
  file:
    dest: "{{ mixer_user.home }}/artwork/{{ event.id }}"
    state: directory
    recurse: yes
    mode: u=rwx,g=rx,o=rx
  become: yes
  become_user: mixer

- name: copy backgrounds
  copy:
    src: "../../../artwork/{{ event.id }}/{{ item }}.png"
    dest: "{{ mixer_user.home }}/artwork/{{ event.id }}"
    mode: u=rw,g=r,o=r
  with_items:
    - side-by-side
    - side-by-side-reverse
    - side-by-side-43
    - side-by-side-43-reverse
    - blank
  become: yes
  become_user: mixer
