---

- name: create artwork directory
  file:
    dest: /opt/artwork
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: copy backgrounds
  copy:
    src: ../../../artwork/{{ event.id }}/{{ item }}.png
    dest: /opt/artwork/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - side-by-side
    - side-by-side-reverse
    - side-by-side-43
    - side-by-side-43-reverse
    - blank
