---

- name: create artwork directory
  file: dest=/opt/voctomix/artwork state=directory
        owner=root group=root mode=0755

- name: copy backgrounds
  copy: src=../../../artwork/{{ event.id }}/{{ item }}.png
        dest=/opt/voctomix/artwork/
  with_items:
    - side-by-side-reverse
    - side-by-side
    - blank

