---

- name: log room for node_exporter
  become: yes
  copy:
    content: "room{type=\"{{ room_type }}\",id=\"{{ room_id }}\"} 1\n"
    dest: "/var/lib/node_exporter/room.prom"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: save room_type into home
  copy:
    content: "{{ room_type }}\n"
    dest: "/home/opentech/room_type"

- name: save room_id into home
  copy:
    content: "{{ room_id }}\n"
    dest: "/home/opentech/room_id"
