---
# directories & code
- name: create voctomix directories
  file: dest={{ item }} state=directory
        owner=root group=root
  with_items:
    - /opt/voctomix/scripts/
    - /opt/voctomix/release/

- name: checkout voctomix release
  git: repo=https://github.com/voc/voctomix
       dest=/opt/voctomix/release/
       version={{ voctomix.version }}
       force=yes
       accept_hostkey=yes

