---

- name: create voctocore config
  template: src="voctocore-config.ini.j2"
            dest="/opt/voctomix/voctocore-config.ini"
            mode=0644 owner=root group=root
  when: voctomix_sources is defined

- name: create voctocore systemd-unit
  template: src="voctocore.service.j2"
            dest="/etc/systemd/system/voctomix-voctocore.service"
            mode=0644 owner=root group=root

- name: reload systemd daemon
  command: systemctl daemon-reload
  changed_when: false

- name: enable & (re)start voctomix-voctocore.service
  service: name=voctomix-voctocore.service
           enabled=yes
           state=restarted
  when: voctocore_enabled == true

- name: disable & stop voctomix-voctocore.service
  service: name=voctomix-voctocore.service
           enabled=no
           state=stopped
  when: voctocore_enabled != true
