---
- hosts: all
  roles:
    - productivity
    - laptop
    - role: cloudalchemy.node-exporter
      tags: node_exporter

- hosts: recorders
  roles:
    - role: recorder

- hosts: audio_source
  roles:
    - role: audio_source

