---
- hosts: recorders
  roles:
    - productivity

- hosts: recorders
  roles:
    - role: laptop
    - role: recorder
    - role: cloudalchemy.node-exporter
      tags: node_exporter
  vars:
    autostart: false
